### ISSUE TITLE
org.testng.reporters.JUnitReportReporter failed

### ISSUE THREAD

**Issue by cheungtitus** [kenrui-group/packetbroker#1]
### Description
When running Maven test lifecycle following is shown in console.
[TestNG] Reporter org.testng.reporters.JUnitReportReporter@5594a1b5 failed
java.util.ConcurrentModificationException

### Environment
* Windows 10
* JDK 1.8.0_162

### Steps to reproduce
1. Uncomment line https://github.com/kenrui-group/packetbroker/blob/b32d2b25aba68afbc0176387f599cd5842c8ba0c/pom.xml#L178

2. Run Maven Test

### Expected behaviour
No exceptions.

### Actual behaviour
Exception thrown.

### Error Message & Stack Trace
```
[TestNG] Reporter org.testng.reporters.JUnitReportReporter@5594a1b5 failed
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909)
	at java.util.ArrayList$Itr.next(ArrayList.java:859)
	at org.testng.reporters.JUnitReportReporter.getNextConfiguration(JUnitReportReporter.java:220)
	at org.testng.reporters.JUnitReportReporter.generateReport(JUnitReportReporter.java:105)
	at org.testng.TestNG.generateReports(TestNG.java:1175)
	at org.testng.TestNG.run(TestNG.java:1102)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:135)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:193)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:94)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:379)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:340)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:413)
```

**Comment by cheungtitus** [comment]
This is due to reported issue.  TestNG 6.10 fixes this issue.
https://github.com/cbeust/testng/issues/1168
